[tox]
skipsdist = True
envlist = py37, py38, py39, lint

[testenv:lint]
deps =
    .[test]
commands =
    flake8 dr_simulator --count --verbose --show-source --statistics
    black --check dr_simulator

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    .[test]
commands =
    pytest --basetemp={envtmpdir} --cov-report html --cov=dr_simulator dr_simulator/tests/
