"""This module contains the data structures used in the demand response simulator."""

# Demand response parameters
DR_NAME_KEY = "name"
DR_EVENT_DETAILS_KEY = "events detail"
DR_DAY_KEY = "day"
DR_MONTH_KEY = "month"
DR_YEAR_KEY = "year"
DR_DURATION_KEY = "duration"
DR_START_TIME_KEY = "start_time"
DR_SIMILAR_WEEKDAYS_KEY = "baseline_days"
DR_EVENT_HOURS_DATA_KEY = "event hours data"
DR_BASELINE_CONSUMPTION_KEY = "baseline consumption"
DR_INDICATOR_ARRAY_KEY = "indicator array"
DR_CAPACITY_PRICE_KEY = "reduction compensation"
DR_CAPACITY_BID_KEY = "reduction capacity"
DR_DAY_OF_ADJUSTMENT_KEY = "day of adjustment"
DR_MAXIMUM_KEY = "maximum"
DR_HOURS_BEFORE_KEY = "hours before"
DR_PAYMENT_FUNCTION_KEY = "payment function"
DR_DOMAIN_KEY = "domain"
DR_SLOPE_KEY = "slope"
DR_INTERCEPT_KEY = "intercept"
DR_EVENTS_PERIODS_KEY = "dr events periods"
DR_EVENTS_PARAMETERS_KEY = "dr event parameters"
